# Generated by Django 6.1 on 2026-08-16 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('image_path', models.CharField(blank=True, max_length=500)),
                ('detector_source', models.CharField(max_length=32)),
                ('detector_quality', models.FloatField(default=0.0)),
                ('used_fallback', models.BooleanField(default=False)),
                ('vlm_latency_ms', models.FloatField(blank=True, null=True)),
                ('vlm_model', models.CharField(blank=True, max_length=64)),
                ('vlm_requests_made', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ScanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spine_index', models.IntegerField()),
                ('raw_title', models.CharField(blank=True, max_length=300, null=True)),
                ('raw_author', models.CharField(blank=True, max_length=300, null=True)),
                ('legible', models.BooleanField(default=False)),
                ('matched_catalog_id', models.CharField(blank=True, max_length=32, null=True)),
                ('matched_title', models.CharField(blank=True, max_length=300, null=True)),
                ('matched_author', models.CharField(blank=True, max_length=300, null=True)),
                ('confidence', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('auto', 'Auto'), ('review', 'Review'), ('unmatched', 'Unmatched')], default='unmatched', max_length=16)),
                ('reasons', models.JSONField(default=list)),
                ('confirmed', models.BooleanField(default=False)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.scan')),
            ],
            options={
                'ordering': ('spine_index',),
            },
        ),
        migrations.CreateModel(
            name='ConfirmedBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalog_id', models.CharField(blank=True, max_length=32, null=True)),
                ('title', models.CharField(max_length=300)),
                ('author', models.CharField(blank=True, max_length=300, null=True)),
                ('confirmed_at', models.DateTimeField(auto_now_add=True)),
                ('scan_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='confirmation', to='api.scanitem')),
            ],
            options={
                'ordering': ('-confirmed_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='scanitem',
            constraint=models.UniqueConstraint(fields=('scan', 'spine_index'), name='unique_spine_index_per_scan'),
        ),
    ]
